name: Building Base Image

on:
  workflow_dispatch:

jobs:
  hirte-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y install podman 

      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build hirte-builder Base Image
        run: |
          podman build -f tests/Containerfile-build -t ghcr.io/containers/hirte-image:latest .
          podman push ghcr.io/containers/hirte-image:latest
